### ISSUE TITLE
Cannot start SSR dev

### ISSUE THREAD

**Issue by breberafilip** [frandiox/vitessedge-template#1]
Hello, I cloned the repository and tried to run the SSR dev environment with `yarn dev` and console is throwing type errors and I basically can't start it whatsoever. I tried to fix these issues, but every time I try to open preview in browser it ends due to this TypeError:
 ```
TypeError: Request is not a constructor
    at IncomingMessage.<anonymous> (file:///Users/brebera/Downloads/vitessedge-template-master%203/node_modules/vitedge/dev/middleware.js:21:9)
    at IncomingMessage.emit (events.js:315:20)
    at IncomingMessage.EventEmitter.emit (domain.js:485:12)
    at endReadableNT (_stream_readable.js:1225:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
✨  Done in 9.51s.
 ```
 
 
 These are the errors that I've been getting right after the clone:

 ```
SyntaxError: The requested module 'vite-plugin-pwa' does not provide an export named 'VitePWA'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at Loader.import (internal/modules/esm/loader.js:179:24)
    at importModuleDynamicallyWrapper (internal/vm/module.js:432:15)
    at loadConfigFromFile (/Users/brebera/Downloads/vitessedge-template-master 3/node_modules/vite/dist/node/chunks/dep-66eb515d.js:46226:31)
    at Object.resolveConfig (/Users/brebera/Downloads/vitessedge-template-master 3/node_modules/vite/dist/node/chunks/dep-66eb515d.js:45889:28)
    at resolveHttpServer (/Users/brebera/Downloads/vitessedge-template-master 3/node_modules/vite-ssr/dev/server.js:31:20)
    at Object.createSsrServer [as default] (/Users/brebera/Downloads/vitessedge-template-master 3/node_modules/vite-ssr/dev/server.js:66:24)
```

after removing VitePWA: 
```
SyntaxError: The requested module 'vite' does not provide an export named 'defineConfig'
    at ModuleJob._instantiate (internal/modules/esm/module_job.js:92:21)
    at ModuleJob.run (internal/modules/esm/module_job.js:107:20)
    at Loader.import (internal/modules/esm/loader.js:179:24)
    at importModuleDynamicallyWrapper (internal/vm/module.js:432:15)
```

**Comment by fimbault** [comment]
I've got the same issue

**Comment by frandiox** [comment]
@breberafilip @fimbault What version of Node are you using?
I just tried installing fresh dependencies using Node@v14.16.1 and didn't run into any issue 🤔 (tried with both Yarn and NPM).

**Comment by fimbault** [comment]
@frandiox you're right, works with the LTS version, thxs

**Comment by frandiox** [comment]
I've updated the minimum Node version in `package.json` to `14.16`, which should work fine 👍
